-- Create user for the application
CREATE USER mvtipbtc_user IDENTIFIED BY mvtipbtc_password;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE, DBA TO mvtipbtc_user;
GRANT CREATE SESSION TO mvtipbtc_user;
GRANT CREATE TABLE TO mvtipbtc_user;
GRANT CREATE SEQUENCE TO mvtipbtc_user;
GRANT CREATE VIEW TO mvtipbtc_user;
GRANT CREATE PROCEDURE TO mvtipbtc_user;
GRANT CREATE TRIGGER TO mvtipbtc_user;
GRANT UNLIMITED TABLESPACE TO mvtipbtc_user;

-- Connect as the new user
CONNECT mvtipbtc_user/mvtipbtc_password;

-- Create tables (these will be auto-created by Hibernate, but included for reference)
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction_analyses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR2(255) NOT NULL,
    risk_score NUMBER(3) NOT NULL,
    risk_level VARCHAR2(50) NOT NULL,
    transaction_volume NUMBER(19,8),
    network_confirmations NUMBER(10),
    first_seen TIMESTAMP,
    total_received NUMBER(19,8),
    total_sent NUMBER(19,8),
    current_balance NUMBER(19,8),
    number_of_transactions NUMBER(10),
    analysis CLOB,
    mixing_probability NUMBER(3),
    illicit_fund_sources NUMBER(3),
    dark_market_connections NUMBER(3),
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR2(100) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    risk_level VARCHAR2(50) NOT NULL,
    address VARCHAR2(255),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE reports (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(255) NOT NULL,
    s3_key VARCHAR2(500) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    report_type VARCHAR2(100) NOT NULL,
    user_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_transaction_analyses_address ON transaction_analyses(address);
CREATE INDEX idx_transaction_analyses_user_id ON transaction_analyses(user_id);
CREATE INDEX idx_alerts_user_id ON alerts(user_id);
CREATE INDEX idx_alerts_risk_level ON alerts(risk_level);
CREATE INDEX idx_reports_user_id ON reports(user_id);
CREATE INDEX idx_reports_address ON reports(address);

